## Assignment 3: $k$ Nearest Neighbor

**Do two questions.**

`! git clone https://github.com/DS3001/knn`

In [1]:
! git clone https://github.com/DS3001/knn

Cloning into 'knn'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 40 (delta 10), reused 2 (delta 2), pack-reused 25
Receiving objects: 100% (40/40), 11.00 MiB | 14.80 MiB/s, done.
Resolving deltas: 100% (13/13), done.


In [2]:

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.neighbors import KNeighborsRegressor

**Q1.** This question is a case study for $k$ nearest neighbor The target variable `y` is `price` and the features are `year` and `mileage`.

1. Load the `./data/USA_cars_datasets.csv`. Keep the following variables and drop the rest: `price`, `year`, `mileage`. Are there any `NA`'s to handle? Look at the head and dimensions of the data.
2. Maxmin normalize `year` and `mileage`.
3. Split the sample into ~80% for training and ~20% for evaluation.
4. Use the $k$NN algorithm and the training data to predict `price` using `year` and `mileage` for the test set for $k=3,10,25,50,100,300$. For each value of $k$, compute the mean squared error and print a scatterplot showing the test value plotted against the predicted value. What patterns do you notice as you increase $k$?
5. Determine the optimal $k$ for these data.
6. Describe what happened in the plots of predicted versus actual prices as $k$ varied, taking your answer into part 6 into account. (Hint: Use the words "underfitting" and "overfitting".)

In [3]:
df = pd.read_csv('/content/knn/data/USA_cars_datasets.csv')
df.head()
print(df.keys())
# want to keep price, year, mileage
df.pop('Unnamed: 0')
df.pop('brand')
df.pop('model')
df.pop('title_status')
df.pop('color')
df.pop('vin')
df.pop('lot')
df.pop('state')
df.pop('country')
df.pop('condition')
df.head()


Index(['Unnamed: 0', 'price', 'brand', 'model', 'year', 'title_status',
       'mileage', 'color', 'vin', 'lot', 'state', 'country', 'condition'],
      dtype='object')


price  year  mileage
0   6300  2008   274117
1   2899  2011   190552
2   5350  2018    39590
3  25000  2014    64146
4  27700  2018     6654

In [4]:
def maxmin(z): #year and mileage
    z = (z-min(z))/(max(z)-min(z))
    return(z)
y = df['year']
x = df.loc[:,['year', 'mileage']]
#print(x.head())
#print(x.describe())
x = x.apply(maxmin)
print(x.head())
print(x.describe())

       year   mileage
0  0.744681  0.269287
1  0.808511  0.187194
2  0.957447  0.038892
3  0.872340  0.063016
4  0.957447  0.006537
              year      mileage
count  2499.000000  2499.000000
mean      0.930091     0.051377
std       0.073248     0.058654
min       0.000000     0.000000
25%       0.914894     0.021088
50%       0.957447     0.034742
75%       0.978723     0.062354
max       1.000000     1.000000



3. Split the sample into ~80% for training and ~20% for evaluation.

4. Use the  𝑘 NN algorithm and the training data to predict price using year and mileage for the test set for  𝑘=3,10,25,50,100,300 . For each value of  𝑘 , compute the mean squared error and print a scatterplot showing the test value plotted against the predicted value. What patterns do you notice as you increase  𝑘 ?

In [ ]:
# fitting the data set
from sklearn.model_selection import train_test_split # Split the sample 80 train/ 20 test
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2,random_state=100)
k_list = [3, 10, 25, 50, 100, 300]
SSE = np.zeros(k_list)
training_SSE = np.zeros(k_list)
#kNN
for k in k_list:
    model = KNeighborsRegressor(n_neighbors=k+1) # Create a sk model for k
    fitted_model = model.fit(x_train,y_train) # Fitting model on training data
    y_predict = fitted_model.predict(x_test) # Predict values for test set
   # SSE[k] = np.sum( (y_test-y_predict)**2 ) # computes SSE for test set
    y_hat = fitted_model.predict(x_train) # Predict values for training set
    #training_SSE[k] = np.sum( (y_train-y_predict)**2 ) # computes SSE for training set
    #sns.scatterplot (data = df, x = x_test, y= y)

SSE_min = np.min(SSE) # Lowest recorded SSE
min_index = np.where(SSE==SSE_min) # Find the indices of y that equal the minimum
k_star = min_index[0]+1 # Find the optimal value of k, we want the k w/ the lowest MSE
print(k_star)
plt.plot(np.arange(0,k_list),SSE,label='Test') # Plot SSE by k
plt.xlabel("k")
plt.ylabel("SSE")
plt.legend(loc='upper right')
plt.title('SSE')
plt.show()

**Q2.** This question is a case study for $k$ nearest neighbor. The data for the question include:

- age: age of the patient (years)
- anaemia: decrease of red blood cells or hemoglobin (boolean)
- high blood pressure: if the patient has hypertension (boolean)
- creatinine phosphokinase (CPK): level of the CPK enzyme in the blood (mcg/L)
- diabetes: if the patient has diabetes (boolean)
- ejection fraction: percentage of blood leaving the heart at each contraction (percentage)
- platelets: platelets in the blood (kiloplatelets/mL)
- sex: woman or man (binary)
- serum creatinine: level of serum creatinine in the blood (mg/dL)
- serum sodium: level of serum sodium in the blood (mEq/L)
- smoking: if the patient smokes or not (boolean)
- time: follow-up period (days)
- death event: if the patient deceased during the follow-up period (boolean)

1. Load the `./data/heart_failure_clinical_records_dataset.csv`. Are there any `NA`'s to handle? use `.drop()` to remove `time` from the dataframe.
2. Make a correlation matrix. What variables are strongly associated with a death event?
3. For the dummy variables `anaemia`, `diabetes`, `high_blood_pressure`, `sex`, and `smoking`, compute a summary table of `DEATH_EVENT` grouped by the variable. For which variables does a higher proportion of the population die when the variable takes the value 1 rather than 0?
4. On the basis of your answers from 2 and 3, build a matrix $X$ of the variables you think are most predictive of a death, and a variable $y$ equal to `DEATH_EVENT`.
5. Maxmin normalize all of the variables in `X`.
6. Split the sample into ~80% for training and ~20% for evaluation. (Try to use the same train/test split for the whole question, so that you're comparing apples to apples in the questions below.).
7. Determine the optimal number of neighbors for a $k$NN regression for the variables you selected.
8. OK, do steps 5 through 7 again, but use all of the variables (except `time`). Which model has a lower Sum of Squared Error? Which would you prefer to use in practice, if you had to predict `DEATH_EVENT`s? If you play with the selection of variables, how much does the SSE change for your fitted model on the test data? Are more variables always better? Explain your findings.

In [47]:
df = pd.read_csv('/content/knn/data/heart_failure_clinical_records_dataset.csv')
#df.head() ; no NAs
df= df.drop('time' ,axis= 'columns') #remove time
df.head()
print(df.columns)





Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'DEATH_EVENT'],
      dtype='object')


In [50]:
#correlation matrix
index = df.columns
for i in index:
  matrix = np.corrcoef(df[i],df['DEATH_EVENT'])
  print (i)
  print(matrix)

age
[[1.         0.25372854]
 [0.25372854 1.        ]]
anaemia
[[1.        0.0662701]
 [0.0662701 1.       ]]
creatinine_phosphokinase
[[1.         0.06272816]
 [0.06272816 1.        ]]
diabetes
[[ 1.         -0.00194288]
 [-0.00194288  1.        ]]
ejection_fraction
[[ 1.         -0.26860331]
 [-0.26860331  1.        ]]
high_blood_pressure
[[1.         0.07935106]
 [0.07935106 1.        ]]
platelets
[[ 1.         -0.04913887]
 [-0.04913887  1.        ]]
serum_creatinine
[[1.         0.29427756]
 [0.29427756 1.        ]]
serum_sodium
[[ 1.        -0.1952036]
 [-0.1952036  1.       ]]
sex
[[ 1.         -0.00431638]
 [-0.00431638  1.        ]]
smoking
[[ 1.         -0.01262315]
 [-0.01262315  1.        ]]
DEATH_EVENT
[[1. 1.]
 [1. 1.]]


3. For the dummy variables anaemia, diabetes, high_blood_pressure, sex, and smoking, compute a summary table of DEATH_EVENT grouped by the variable. For which variables does a higher proportion of the population die when the variable takes the value 1 rather than 0?

4. On the basis of your answers from 2 and 3, build a matrix  𝑋  of the variables you think are most predictive of a death, and a variable  𝑦 equal to DEATH_EVENT.

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking  DEATH_EVENT  
count         299.00000    299.000000  299.000000  299.00000    299.00000  
mean            1.39388    136.625418    0.648829    0.32107      0.32107  
std             1.03451      4.412477    0.478136    0.46767      0.46767  
min             0.50000    113.000000    0.000000    0.00000      0.00000  
25%             0.90000    134.000000    0.000000    0.00000      0.00000  
50%             1.10000    137.000000    1.000000    0.00000      0.00000  
75%             1.40000    140.000000    1.000000    1.00000      1.00000  
max             9.40000    148.000000    1.000000    1.00000      1.00000

The matrix indicates a high correlation between age and the risk of death as well as serum creatine and risk of death.

**Q3.** Let's do some very basic computer vision. We're going to import the MNIST handwritten digits data and $k$NN to predict values (i.e. "see/read").

1. To load the data, run the following code in a chunk:
```
from keras.datasets import mnist
df = mnist.load_data('minst.db')
train,test = df
X_train, y_train = train
X_test, y_test = test
```
The `y_test` and `y_train` vectors, for each index `i`, tell you want number is written in the corresponding index in `X_train[i]` and `X_test[i]`. The value of `X_train[i]` and `X_test[i]`, however, is a 28$\times$28 array whose entries contain values between 0 and 256. Each element of the matrix is essentially a "pixel" and the matrix encodes a representation of a number. To visualize this, run the following code to see the first ten numbers:
```
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000)
for i in range(5):
    print(y_test[i],'\n') # Print the label
    print(X_test[i],'\n') # Print the matrix of values
    plt.contourf(np.rot90(X_test[i].transpose())) # Make a contour plot of the matrix values
    plt.show()
```
OK, those are the data: Labels attached to handwritten digits encoded as a matrix.

2. What is the shape of `X_train` and `X_test`? What is the shape of `X_train[i]` and `X_test[i]` for each index `i`? What is the shape of `y_train` and `y_test`?
3. Use Numpy's `.reshape()` method to covert the training and testing data from a matrix into an vector of features. So, `X_test[index].reshape((1,784))` will convert the $index$-th element of `X_test` into a $28\times 28=784$-length row vector of values, rather than a matrix. Turn `X_train` into an $N \times 784$ matrix $X$ that is suitable for scikit-learn's kNN classifier where $N$ is the number of observations and $784=28*28$ (you could use, for example, a `for` loop).
4. Use the reshaped `X_test` and `y_test` data to create a $k$-nearest neighbor classifier of digit. What is the optimal number of neighbors $k$? If you can't determine this, play around with different values of $k$ for your classifier.
5. For the optimal number of neighbors, how well does your predictor perform on the test set?
6. So, this is how computers "see." They convert an image into a matrix of values, that matrix becomes a vector in a dataset, and then we deploy ML tools on it as if it was any other kind of tabular data. To make sure you follow this, invent a way to represent a color photo in matrix form, and then describe how you could convert it into tabular data. (Hint: RGB color codes provide a method of encoding a numeric value that represents a color.)

In [ ]:
**Q4.**